### ISSUE TITLE
Send requests to localhost

### ISSUE THREAD

**Issue by Qasym** [mirasnag/budget-sync#1]
Hi, @mirasnag,

I forked your project for one of my personal projects, I wanted to create a working backend for your application.
I would like to request you to make a branch where all data is being sent to [http://localhost:8989](http://localhost:8989) instead of being stored in cache (I noticed some parts of the code using `localStorage`)

Additionally, since I need to know what kind of data is used in your app, I also wanted to ask you to write out a documentation, that will help me out to generate a proper backend.

Looking forward to hearing from you

Thanks!

**Comment by mirasnag** [comment]
Hi @Qasym,

Thank you for forking my project and your interest in creating a backend for it! I appreciate your effort in reaching out.

I have completed the requested changes and created a new branch "backend" where all data is sent to http://localhost:8989 instead of being stored in localStorage. Please feel free to check it out and let me know if you have any questions or need further adjustments.

Additionally, I have finished the documentation, which describes the data models used in the app. However, please note that there might be some minor changes to the data models as I continue refining the application. I will keep you updated on any changes.

Looking forward to seeing how your backend turns out!

Thanks again!
